### ISSUE TITLE
[Feature Request] Autodetect languages / allow to choose multiple languages

### ISSUE THREAD

**Issue by mathiasconradt** [janis91/ocr#128]
Currently you can only select one language. In most cases it's fine. But it would be nice if there would be a either an automatic language detection or if you could just simply pass all possible languages as parameter, i.e.  `-l eng -l deu`

This should work for images as well as OcrMyPdf.

Related: 
https://github.com/janis91/ocr/issues/121
https://github.com/jbarlow83/OCRmyPDF/issues/39

**Comment by janis91** [comment]
@mathiasconradt I think this is already possible. I don't know if I just didn't close this or whatever.. I'll close it now.

**Comment by stweil** [comment]
Selecting more than one language works fine.

With Tesseract 4 it will also be possible to select scripts instead of languages. Scripts cover several languages, for example `Latin` (with `Latin.traineddata`) includes not only English but all Western European languages.

**Comment by janis91** [comment]
@stweil I didn't take the chance to look deeper into tess4, just yet. Of course it seems very promising and new things are introduced with it. Unfortunately, last time I tried the alpha version it was really really slow. ca factor 30. I tried it with my local test files for the app development of ocr and it really needed about 30 seconds for a simple image that just needs a second or two when using tess3. So I decided to package tess3 into the docker container. If this improved and is stable and you got more experience with it, I would appreciate it very much to hear from you or maybe get another PR for the dockerfile putting things together, as well! :-)
Just fyi.

**Comment by stweil** [comment]
You will need the `traineddata` files from http://github.com/tesseract-ocr/tessdata_fast. Depending on the language, recognition with Tesseract 4 and those files is only slightly slower or even faster than Tesseract 3. That's why those files are now part of the new tesseract-ocr packages for Debian / Ubuntu.

Tesseract 4 uses up to 4 threads during the OCR by default while Tesseract 3 was single threaded. This is good if your CPU has at least 4 available cores per Tesseract process, but performance drops dramatically if you have too few cores. As OCRmyPDF runs one Tesseract process per core to handle several pages simultaneously, this is the worst case: for n cores there will be n processes with 4 threads, so 4 threads run per core. It is therefore essential to disable Tesseract's multithreading in combination with OCRmyPDF. That can be done by setting environment variable `OMP_THREAD_LIMIT=1`.
