### ISSUE TITLE
Using available redis installation with linux sockets

### ISSUE THREAD

**Issue by blubbsy** [janis91/ocr#163]
Hi,

is it possible to use the ocr docker container also in combination with a already installed redis installation that works with linux sockets? I'm trying already a little bit to get it working, but at the moment i wasnt successfull. If it is not possible i will simply build the redis container, i just dont like software doubled ;) 

BR,
B

**Comment by blubbsy** [comment]
I tried several things, but couldnt get it working with linux sockets. any recommendations, except changing to TCP/IP ports?

**Comment by rarapost** [comment]
I also tested this feature and found it not working. I would invite this functionality since unix domain socket is faster, less resources consuming and more secure then TCP.

**Comment by janis91** [comment]
I won't support anything prior version 4, because the whole setup is just too much effort. I will close this issue now and hope that version 4 (which will be shipped in a few weeks probably) will fill your need. If not. please feel free to fork the repo and work on the old code base which will reside in the branch "not-maintained".
