### ISSUE TITLE
(NC 10.0.1) while installing: Array to string conversion 

### ISSUE THREAD

**Issue by daita** [janis91/ocr#21]
I downloaded the master.zip and the 0.8.8: same error.

I put the folder in apps/ and open the App webpage. Can't display the list of disabled appsand I got this message:

Array to string conversion at /home/www/kh.ro/dev/nextcloud-dev/settings/Controller/AppSettingsController.php#238

I had to remove the german version in the info.xml (name/summary/description) :

```
<name>OCR</name>
<summary >Character recoginition for your images and pdf files.</summary>
<description><![CDATA[# Description
[![Build Status](https://travis-ci.org/janis91/ocr.svg?branch=master)](https://travis-ci.org/janis91/ocr) [![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/janis91/ocr/badges/quality-score.png?b=master)](https://scrutinizer-ci.c$
**This software is in beta phase 
[...]
```

**Comment by janis91** [comment]
Hi, thanks for your test. the following is the reason and should be backported to version 9 and 10 as far as i know:
Issue on nextcloud/server:
https://github.com/nextcloud/server/issues/1466

Initial issue:
https://github.com/janis91/nextnotes/issues/31

Should already be fixed within the master branch.. (just look up the conversation in the nextcloud issue).
Closed because the fix is provided by nextcloud.

**Comment by janis91** [comment]
https://help.nextcloud.com/t/blank-page-on-enabled-apps-after-installing-ocr-1-0-0/5812/5?u=janis91
