### ISSUE TITLE
OCR/fulltextsearch/tesseract

### ISSUE THREAD

**Issue by Niemand112233** [janis91/ocr#237]
What is the difference between all of these apps?! I'm lost.

**Comment by danielrheinbay** [comment]
* The [OCR app](https://apps.nextcloud.com/apps/ocr), i.e. this app, does the actual ocr process (optical character recognition) _in your browser on your client_ using very powerful JavaScript libraries. You can use the OCR app on demand. It creates a separate file containing the text.
* The [Full text search app](https://apps.nextcloud.com/apps/fulltextsearch) is a framework. It contains e.g. a frontend which you can use to enter search queries, but it does not index any file contents itself. Instead, it relies on extensions to scan contents, e.g. [Files](https://apps.nextcloud.com/apps/files_fulltextsearch) to index your files or [Bookmarks](https://apps.nextcloud.com/apps/bookmarks_fulltextsearch) to index your bookmarks. Unlike the OCR app, these extensions run in the background, i.e. not on demand. Also, unlike the OCR app, these extensions index your files on the server, i.e. not on your client.
* [Tesseract](https://github.com/tesseract-ocr/tesseract) is free, open source software to do optical character recognition. The [Full text search - Files - Tesseract OCR app](https://apps.nextcloud.com/apps/files_fulltextsearch_tesseract) uses Tesseract to scan the contents of files and add them to your full text search index. The [OCR app](https://tesseract.projectnaptha.com/) also uses Tesseract to scan the contents of your files, but since it runs in your browser, it uses a JavaScript port called [Tesseract.js](https://github.com/naptha/tesseract.js).
