### ISSUE TITLE
In a local network Tessdata cannot be downloaded from github

### ISSUE THREAD

**Issue by lnyk** [janis91/ocr#239]
# Bug report
## Current Behavior
First of all, thanks for the wonderful ocr app you guys gave us!

I cannot use it, in my firefox dev-tools panel, I got an network error after the ocr app queued an image and started to work, the page just hang there forever.

I'm running NextCloud in a local network and cannot connect to the Internet and fetch data from github...

## Possible Solution

If there's a way to store tessdata files locally...

## Steps to Reproduce (for bugs)
Reproduce... Just unplug your cable...

## Your Environment
NextCloud Docker image in Local Network.

**Comment by janis91** [comment]
Initially I used to bundle all tessdata with the app to load it from the local server. Unfortunately the app's bundle size is too big when I did it like that. I have an idea to get around this (add a migration step, that downloads the tessdata) but it's not yet added. I will add it as soon as I can.

**Comment by janis91** [comment]
The linked PR will add the requested feature. Please be aware of the following: In order to install the tessdata manually (in case the server doesn't have a internet connection and hence cannot download it automatically), you'll have to:
1. deactivate/disable the ocr app
2. create `ocr/tessdata` folder in the `appdata_<instanceid>` folder
3.  add all required traineddata files (from: [tessdata](https://github.com/janis91/tessdata/) - I recommend the "fast" version)
4. execute `occ files:scan-app-data` for rescanning your appdata (may take a bit depending on the size of your appdata folder)
5. Activate ocr app again (it will recognize that tessdata is already existing)
