### ISSUE TITLE
OCR increases file size on factor 4 to 11

### ISSUE THREAD

**Issue by mokkin** [janis91/ocr#251]
## Context
The file size of the ocr results is much larger than the original file, example here with factor 4. I have another example where it is more than 10 times more.

[Scannen_ocr.pdf](https://github.com/janis91/ocr/files/4104318/Scannen_ocr.pdf)
[Scannen.pdf](https://github.com/janis91/ocr/files/4104319/Scannen.pdf)

In my point of view, ocr shoul add only a "text layer" to the document, but not modify the embedded pictures.

## Your Environment

* OCR version used: 5.0.3
* Browser Name and version: FF 72.0.7
* Operating System and version (desktop or mobile): Manjaro
* nextcloud version: (see admin page or version.php) 17.0.2
* PHP version 7.3
* Database version SQLite
* Are you using encryption: yes/no no

**Comment by janis91** [comment]
You're right and at the moment that is kind of "expected" behavior. The thing is:
The app uses tesseract.js inside of it in order to transform pictures (png, jpeg, etc.) into pdf containing the picture and a text layer (like you pointed out already). When you hand a picture to the app, this is really straight forward. But in case of a pdf, there happens a lot of stuff beforehand. Tesseract.js does not accept PDF as input type. Therefore the app needs to kind of extract the pdf pages and convert them into a format, tesseract understands. The easiest way of doing that, is to draw the pdf on a HTML Canvas Element, because tesseract.js accepts canvas elements as input. I guess the main problem here is, that the canvas element does not use any kind of compression such as pdf most likely does. So I guess the main cause for this, is that we use the canvas as input instead of for example a jpeg or png which has compression. Canvas is more like bmp (no compression at all). I guess it could be possible to dive deeper into the PDF insights and take the original picture out of a pdf instead of doing it like described. That could probably improve this behavior. I am not a PDF expert, so I need to look into it. I will mark this as a "Feature request".

**Comment by janis91** [comment]
I really dived deep into the possibilities of pdfjs and pdf-lib. At the moment I don't see a simple possibility to get what is needed. I guess the best way would be to simplify the app once more. The idea would be to only support images and ignore pdfs completely. Almost all scanners out there should be able to save pages as images (png or jpeg). I could create another app that supports merging, re-arranging, ... pdf documents. That could be beneficial for even more people.

**Comment by DecaTec** [comment]
I stumbled upon the same issue. The app is really useful, but creates huge output files.
So for creating OCRed documents, I now use a bash script which is run by cron and watches for specific files in a predefined (NC) directory (mounted as external (local) storage).

I'm not an expert on NC app development, but would it be possible not using tesseract.js, but call a bash script directly?

Here's the script I'm talking about: https://codeberg.org/DecaTec/OCRmyFiles

**Comment by janis91** [comment]
@DecaTec The problem is not tesseract.js. It's the pdf file handling in the browser. Because of that I removed support of PDF input files from this app from v6.0.0. Of course you can use a bash script, but this requires additional setup on the server, which is more complicated than this. 
The main purpose of this app is to have a simple setup (single installation from the app store). And NOT to require an adminstrator to install and configure many things on the server side. 

Until v4 this app required an installation of tesseract and ocrmypdf, but it caused many bugs and problems with different types of OS NC was running on. For example on BSD based sytems it was literally impossible to get the setup working. Instead of trying to generalize more and more, I started with a new approach: Client-side tesseract.

From v6 now the app won't accept PDF input files anymore and it focuses on what tesseract is able to do best: image input => pdf output (without any increase in file size anymore)

I plan to add another app that handles pdfs in order to for example merge and split them etc. But I won't go server-side in combination with php anymore. Don't get me wrong but I do this in my free time and do want to do php as less as possible. IMHO it's not enterprise grade and modern at all. Testing is ridiculous and type support is also really low level.

I'm not completely up to date with NC18 but maybe it's possible to add a "workflow" with your script in order to add ocrmypdf to NC for you.

**Comment by DecaTec** [comment]
Yes, I can understand that.
Thanks for the clarification!

Good point with the idea of workflows: I'll give it a try.
