### ISSUE TITLE
Support for Nextcloud v19

### ISSUE THREAD

**Issue by rakekniven** [janis91/ocr#276]
Updater for NC19 RC3 says :

This app has no update available for NC 19

Can you please have a look?

Thank you

**Comment by e-alfred** [comment]
I tested the app on Nextcloud 19 and it works well so far. @janis91 can you create a new release for Nextcloud 19?

**Comment by rakekniven** [comment]
Same here.

**Comment by rakekniven** [comment]
Hello @janis91 ,

just installed latest release on my NC19. Still it says unsupported. Could you please adapt the app to be ready for NC19?

Can I help you in anyway?

Best regards.

**Comment by rakekniven** [comment]
Hello @janis91 , just seen you did some releases the last days.
Is the app working now on NC19? It is still marked as not suitable for NC 19.

**Comment by dsiminiuk** [comment]
I'm holding off on an update to NC 19 for this app to be compatible. +1.

**Comment by kristofejro** [comment]
And version 20 is just around the corner

![v20](https://user-images.githubusercontent.com/15168170/91407902-44073f80-e843-11ea-80ce-9dc4fa961e88.JPG)

**Comment by JonathanTreffler** [comment]
It does not seem like this project is maintained anymore 🙁

**Comment by janis91** [comment]
Hi everyone,

first of all: I'm really sorry for not answering here, because typically I try to be as supportive as I can.
I wanted to do the update and some improvements already a couple of months ago, but instead my whole dev setup machine crashed and I'm still not able to set it up again because of other business projects. I will maintain this project further. But at this point I am not able to give a good guess when the update can be provided. I ahve to maintain or develop not only this project and because of that it's unfortunately not as easy as to install php and pull a NC git version. I have to support more than one php version at a time and some more things on the same machine. That's the reason for the long delay.
I hope that I will be back on top by November, such that by then I can put some updates out there.
Sorry for that.
Janis

**Comment by rakekniven** [comment]
Hey @janis91 , good to hear you are still alive and active :-)

**Comment by styx-tdo** [comment]
Have you thought about using GitHub continuous integration?
https://docs.github.com/en/actions/guides/about-continuous-integration
I think the process would be:
* branch
* get CI up
* change things
* when all is green, re-merge
-> Release

maybe i am unterestimating this, though.

**Comment by radoeka** [comment]
Would it be possible to use docker images?  The correct PHP version will be included in the docker  image, making it possible to serve multiple versions with multiple docker images:

- https://github.com/nextcloud/docker
- https://hub.docker.com/_/nextcloud/

The latter shows which NC versions are available.  Setting it up, might not be that easy - but once done it may give a lot of benefit.  I just wonder, whether the docker version includes the template to start a new NC app.  But that is not a question for here.

**Comment by rakekniven** [comment]
Closing here. NC22 is already out.

**Comment by sunjam** [comment]
NC22 being out does not actually mean this issue is resolved.  See open
issue #280 asking for support on version 20.

**Comment by rakekniven** [comment]
I did not write it has been resolved.
NC 19 is already EOL. See https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

> issue #280 asking for support on version 20

Seen that :-)
