### ISSUE TITLE
Bug report: Infinite OCR queue when OCRWorker was not running

### ISSUE THREAD

**Issue by Sanookmakmak** [janis91/ocr#38]
Nextcloud 11.0.0, OCR 2.0.0.

When trying to OCR and OCRWorker ist not running, the OCR queue is getting big and bigger.

After starting OCRWorker, freshly queued documents will be OCR'd, but the old the OCR queue from before won't vanish.

Also Apache log will be filled up a lot.
`"GET /apps/ocr/status HTTP/1.1" 200 997 "`

Can only disable the app at the moment until the bug is fixed.

![907496ba4ea25049089e7ec3020def7cb378af5b](https://cloud.githubusercontent.com/assets/24833757/21642072/39017268-d280-11e6-90bc-358ec631e22e.png)

**Comment by janis91** [comment]
What do you mean with:

> When trying to OCR and OCRWorker ist not running, the OCR queue is getting big and bigger.

If the OCRWorker isn't working the current behaviour is to store the queued documents in the database in the status table. 
So that a javascript function can poll every 4 seconds if the status changed. 
If the status table is empty, it will not show the status message on the top of the window anymore. But if there are still documents in the queue (and the status table, as the status table will be updated by the OCRWorker), it will not disappear.

It would be possible to add an administration option to hide these messages and/or turn off the polling, but then it is not updating the file list after a processed file anymore and you will not see how many files are in the queue.

The main idea of this app is to have the OCRWorker running as long as the server is running. It does not cost much memory nor does it consume much cpu power, as long as in "standby".

Could you please be a little bit more precise, what is your problem with that?

**Comment by fabricat** [comment]
I had the same issue: the conversions launched when the OCRWorker was not working remain always in the queue.

If I launch a conversion after having started the worker, it will be correctly processed: the notification says "OCR: 2 currently pending file in queue".
After a while this second conversion ends successfully, but the message "OCR: 1 currently pending file in queue" remains always there.

**Comment by janis91** [comment]
@fabricat I guess the problem is more like in #35 .
I am currently working on it.

**Comment by Sanookmakmak** [comment]
**@janis91** 

I have installed the OCR app but did not setup the cronjob for OCRWorker so OCRWorker was not running while OCRing. For that now i have an infinite OCR queue.

I have **already deleted the file** in question, OCRWorker is now started by cron and is running all the time, but the queue is still here.

![out](https://cloud.githubusercontent.com/assets/24833757/21780906/98432ed4-d6ad-11e6-8454-f064c55fba29.gif)

**Comment by janis91** [comment]
ok then please see #35 for a quickfix (delete the database entries of the table ocr_status) and wait for my solution to handle these kind of issues.
