### ISSUE TITLE
OCR doesn't start for my files in a shared directory

### ISSUE THREAD

**Issue by joergmschulz** [janis91/ocr#56]
Bug report 

NC Version 11.01, current OCR app.

When I want to OCR a file that has been uploaded by me, but resides on a directory that has been shared to me, OCR will not start but display an error in the log:

`OCP\AppFramework\Db\DoesNotExistException: Did expect one result but found none when executing: query "SELECT file_target FROM *PREFIX*share WHERE file_source = ? AND share_with = ? AND uid_owner = ?"; parameters Array ( [0] => 168228 [1] => current.user[2] => OwnerOfSharedDir ) ; limit ""; offset ""`

When I login as (OwnerOfSharedDir), OCR works fine.

Is this reproducible or shall I do some more tests and provide more info here?

**Comment by janis91** [comment]
I will try to reproduce it.

**Comment by dienteperro** [comment]
I have had an issue similar to this:

I have an external storage (local) folder: /data/data that is used in nextcloud via the external storage app. The folder is owned by www-data (user and group) and it has permissions for writing. The Nextcloud dir is: /var/www/nextcloud

When I try to OCR a file that has being added there, the OCR gives an error, I need to move the file out of this folder in order to perform the OCR task.

Mi errors logs are:
{"reqId":"lDvKrQH7mV5fSfautj2a","remoteAddr":"192.168.1.104","app":"ocr","message":"Exception during ocr service function processing: {\"Exception\":\"OCP\\\\A
ppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"Did expect one result but found none when executing: query \\\"SELECT file_target FROM *PREFIX*sha
re WHERE file_source = ? AND share_with = ? AND uid_owner = ?\\\"; parameters Array\\n(\\n    [0] => 307\\n    [1] => user@testhost.localdomain\\n    [2] =>
 local::\\\/data\\\/data\\\/\\n)\\n; limit \\\"\\\"; offset \\\"\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(373): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT file_tar...', Array, NULL, NULL)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/ocr\\\/lib\\\/Db\\\/ShareMapper.php(42): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT file_tar...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/ocr\\\/lib\\\/Service\\\/OcrService.php(320): OCA\\\\Ocr\\\\Db\\\\ShareMapper->find(307, 'user@testhost.l...', 'local::\\\/data\\\/da...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/ocr\\\/lib\\\/Service\\\/OcrService.php(173): OCA\\\\Ocr\\\\Service\\\\OcrService->buildTargetForShared(Object(OCA\\\\Ocr\\\\Db\\\\File))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/ocr\\\/lib\\\/Controller\\\/OcrController.php(74): OCA\\\\Ocr\\\\Service\\\\OcrService->process(Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/ocr\\\/lib\\\/Controller\\\/Errors.php(35): OCA\\\\Ocr\\\\Controller\\\\OcrController->OCA\\\\Ocr\\\\Controller\\\\{closure}()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/ocr\\\/lib\\\/Controller\\\/OcrController.php(75): OCA\\\\Ocr\\\\Controller\\\\OcrController->handleNotFound(Object(Closure))\\n#7 [internal function]: OCA\\\\Ocr\\\\Controller\\\\OcrController->process(Array, Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Ocr\\\\Controller\\\\OcrController), 'process')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Ocr\\\\Controller\\\\OcrController), 'process')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OcrController', 'process', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/ocr')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php\",\"Line\":289}","level":3,"time":"2017-02-14T16:33:36+00:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/ocr","user":"user@testhost.localdomain","version":"11.0.1.2"}

I'll create a new issue to input more details, but is probable related to this one.

**Comment by janis91** [comment]
The above mentioned ticket will be used for the discussion and more updates regarding this issue. Therefore I close this one.
