### ISSUE TITLE
[Feature Request] Offloading OCR processing to dedicated server

### ISSUE THREAD

**Issue by putt1ck** [janis91/ocr#68]
Feature request
This may already be available and implicit in docs and I've just failed to understand it.
Make it possible to have the OCR work running on another server to help split workloads

On larger installations (250+ users, 1m+ docs) the servers have been specified for the job envisaged. Adding in (the very useful) OCR functionality puts additional load on the frontend server and potentially impacts UX for all users; offloading it reduces impact and also means the OCR server is more easily updated/optimised.

**Comment by janis91** [comment]
If I get you right, you suggest a solution which can be started by docker (for example) and rusn on its own machine in order to process the files separately. The problem I didn't find an answer for yet, is that you would have to transfer files or at least have read permissions and access to the original file locations in order to process them. With large files this causes much traffic. Do you have an idea what a good practice could look like for this?

**Comment by janis91** [comment]
#93 merged
