### ISSUE TITLE
OCR Settings blank

### ISSUE THREAD

**Issue by Happyfeet01** [janis91/ocr#87]
Hello,

on Nextcloud 12 i get this at th personal Setttings.
![ocr](https://cloud.githubusercontent.com/assets/3295104/26398550/1fca66e8-407a-11e7-9a0d-495550d5025a.PNG)

the Worker running with sudo -u pleskuser nohup php /var/www/vhosts/larsmueller.net/nextcloud/apps/ocr/worker/OCRWorker.php

(pleskuser is the same as www-data at an Pleskerver)

# Bug report 

## Current Behavior
Blank OCR entry at personal Settings

## Your Environment

* OCR version used:
* Browser Name and version: Google Chrome
* Operating System and version (desktop or mobile): Desktop
* ownCloud/nextcloud version: Nextcloud 12.0.0
* PHP version 7.15
* Database version: mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
* Are you using encryption: no

## Log File Content (nextcloud/owncloud.log of the "data"-directory)

no logfile entry

**Comment by janis91** [comment]
Thanks for your report. As this bug is already known and reported / taken care of in #53 , I will close this ticket. Actually the appinfo.xml doesn't allow it to install the ocr app on NC12, as I am not ready with the development/testing yet. I am looking forward to be able to release a new version soon.
Cheers,
Janis
